// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALptqEfa8KxSnH8VXV-17-HSiANHnEISM',
    appId: '1:236729608522:android:a6561ff955a4f96b23f9b3',
    messagingSenderId: '236729608522',
    projectId: 'finance-tracker-a6be7',
    storageBucket: 'finance-tracker-a6be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlM5mylW1F2-87L4S2ZrTJOs4eQWiVVs',
    appId: '1:236729608522:ios:d4e9bac35d2f960023f9b3',
    messagingSenderId: '236729608522',
    projectId: 'finance-tracker-a6be7',
    storageBucket: 'finance-tracker-a6be7.appspot.com',
    androidClientId: '236729608522-rd5c4tc5a5b1ci5u60k2b2apssu966o3.apps.googleusercontent.com',
    iosClientId: '236729608522-66h7c4fei4hrv4954236nr8rshgvbenv.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeTracker',
  );
}
